import './styles/style.css'
//import './js/riddle.js'
import { question, source, handleSubmit } from './js/riddle.js'
//import javascriptLogo from './assets/javascript.svg'
//import viteLogo from './assets/vite.svg'
//import heroImg from './assets/hero.png'
